# Generated by Django 5.0.2 on 2024-03-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('surname', models.CharField(max_length=25, verbose_name='Surname')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=25, unique=True, verbose_name='Phone')),
                ('dt_of_reg', models.DateTimeField(blank=True, null=True, verbose_name='Date and time of reg')),
                ('percent_of_discount', models.IntegerField(default=2, verbose_name='Discount')),
                ('current_balance', models.IntegerField(default=0, verbose_name='Bonus Balance')),
                ('money_spent_cus', models.FloatField(default=0, verbose_name='Money spent (AED)')),
                ('next_level', models.IntegerField(default=10000, verbose_name='Кол-во бонусов для дальнейшей скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Al Barsha', max_length=25, unique=True, verbose_name='Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.FloatField(verbose_name='Sum of purchase')),
                ('accumulated_bonuses', models.IntegerField(verbose_name='Received bonuses')),
                ('the_number_of_bonuses_to_be_debited', models.IntegerField(null=True, verbose_name='Written-off bonuses')),
                ('sum_of_purchase', models.FloatField(verbose_name='Sum of sale')),
                ('percent_of_discount', models.IntegerField(verbose_name='Discount')),
                ('current_balance', models.IntegerField(default=0, verbose_name='Bonus Balance')),
                ('dt_of_sale', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time_of_sale', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.customer', to_field='phone', verbose_name='Phone')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.shop', to_field='name', verbose_name='Shop')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ls.shop', to_field='name', verbose_name='Shop'),
        ),
    ]
