# Generated by Django 5.0.2 on 2024-03-12 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='time_of_sale',
        ),
        migrations.AlterField(
            model_name='customer',
            name='dt_of_reg',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date and time of reg'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dt_of_sale',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date and time of sale'),
        ),
    ]
